### ISSUE TITLE
Operation error

### ISSUE THREAD

**Issue by qjy-liveforover** [ShivamThukral/Visual-Servoing#3]
Hello, may I ask if the following documents are missing：
#include <camshift_tracker/image_data.h>
#include <ur5_visual_servoing/joint_angles.h>
#include <ur5_visual_servoing/joint_states.h>

**Comment by paul-chris** [comment]
Have you solve this problem?I have the same problem

**Comment by ShivamThukral** [comment]
These are message file headers. You will have to compile the code to auto-generate these files. 
What you need is `catkin_make`. You can read more about this [here](http://wiki.ros.org/catkin/commands/catkin_make).
